name: getteacher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  circular_countdown_timer: ^0.2.4
  email_validator: ^3.0.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.5+hotfix.2
  fuzzy: ^0.5.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  latext: ^0.5.0
  progress_state_button: ^1.0.4
  shared_preferences: ^2.3.4
  socket_io_client: ^3.0.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  test: ^1.25.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
